### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by lastlink** [joshudson/Emet#1]
could there be some instructions on how to use this?

**Comment by joshudson** [comment]
Feedback. For months I have awaited feedback.

You are quite right, I have forgotten to write a getting started guide. There is, however, copious documentation. The best way to view the documentation is to add the nuget reference to a Visual Studio project and open Object Browser and extend Emet.Filesystems.

The main entry point is Emet.FileSystems.FileSystem. Just about the only thing not discoverable from there is Emet.FileSystems.IOErrors which provides a list of error codes in readonly variables (rather than constants) so that they change with the target platform.

**Comment by lastlink** [comment]
I would argue that it's hard to get feedback without instructions making it hard for users to try it out. You would likely get more downloads and instructions if you showed a few examples. I found out about this from a thread you posted in an dotnet core issue I think.

**Comment by joshudson** [comment]
Almost certainly, and that dotnet core issue and a couple of others is why this exists.

**Comment by joshudson** [comment]
Fixed problem causing xml doc comments to not upload
